# -*- coding: utf-8 -*-
"""SSD_toONNX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndVyWt6BVRMEIjjwid8eqzn1XXaFn9dN
"""

import os
import sys

ROOT = os.getcwd()
WORK = os.path.join(ROOT, "work")
MODEL = "ssdlite_mobilenet_v2_coco_2018_05_09"
os.makedirs(WORK, exist_ok=True)

# force tf2onnx to cpu
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
os.environ['MODEL'] = MODEL
os.environ['WORK'] = WORK

!pip install --user -U tf2onnx
!pip install --user -U onnxruntime

!cd $WORK; wget -q http://download.tensorflow.org/models/object_detection/$MODEL.tar.gz
!cd $WORK; tar zxvf $MODEL.tar.gz

!saved_model_cli show --dir $WORK/$MODEL/saved_model/ --tag_set serve  --signature_def serving_default

!python -m tf2onnx.convert --opset 10 --saved-model $WORK/$MODEL/saved_model --output $WORK/$MODEL.onnx